Implement restriction on login screen
haroonmaqsoodch/ShopGo pull request #15
Opened 2023-07-30 16:13 UTC by nypdonduty

## jira [SG-10](https://shopgoswift.atlassian.net/browse/SG-10)

## Description:
- Added Shake the password field
- Added a red line that appears under the password field
- Show the forgot password button else, keep it hidden

## how to test:
- enter wrong password and tap login
 
screenshots/gif
https://github.com/haroonmaqsoodch/ShopGo/assets/139644156/7fcccae4-b918-409a-80c2-f1b6bf5d11c3

2023-07-31 13:39 UTC, 05Waleed commented on ShopGo/Login/DismissKeyboard+extension.swift
Ali, why did you submit this file in Waqas bhai PR?

2023-07-31 14:23 UTC, 05Waleed commented on ShopGo/Login/LoginViewController.swift
password extension file is missing.
<img width="1440" alt="Screenshot 2023-07-31 at 16 19 35" src="https://github.com/haroonmaqsoodch/ShopGo/assets/139551937/86c65edc-abf3-4f91-aca4-9124e025dee3">

2023-07-31 17:26 UTC, aliahmed1105 commented on ShopGo/Login/DismissKeyboard+extension.swift
I submitted this file in the PR because I noticed that the file didn't upload properly, so I just deleted it and put it back together.

2023-08-01 22:07 UTC, zuhair5 commented
The rest looks fine, but I still can't see the passwordTextfield + extension file shown in your commits. The file is still missing so kindly recheck and re-commit if possible.

2023-08-01 22:08 UTC, zuhair5 requested changes
The rest looks fine, but I still can't see the **passwordTextfield + extension** file shown in your commits. The file is still missing so kindly recheck and re-commit if possible.

**screenshot**

<img width="1431" alt="Screenshot 2023-08-02 at 3 09 23 AM" src="https://github.com/haroonmaqsoodch/ShopGo/assets/63094797/3a3624f3-a301-4e03-a0e6-70914d2bfdbd">

2023-08-02 17:44 UTC, nypdonduty commented on ShopGo/Login/LoginViewController.swift
solved this problem. please check again.

2023-08-02 17:45 UTC, nypdonduty commented
https://github.com/haroonmaqsoodch/ShopGo/assets/139644156/196b799c-4ab6-4347-a407-dd3b13d2114c

please check again everyone.

2023-08-02 17:47 UTC, nypdonduty commented
> The rest looks fine, but I still can't see the **passwordTextfield + extension** file shown in your commits. The file is still missing so kindly recheck and re-commit if possible.
> 
> **screenshot**
> 
> <img alt="Screenshot 2023-08-02 at 3 09 23 AM" width="1431" src="https://user-images.githubusercontent.com/63094797/257653107-3a3624f3-a301-4e03-a0e6-70914d2bfdbd.png">

Fixed. 

<img width="1469" alt="PasswordTextFieldFile" src="https://github.com/haroonmaqsoodch/ShopGo/assets/139644156/973d2d27-ff25-4835-8745-7325c39d0061">

2023-08-02 18:32 UTC, zuhair5 approved these changes
Seems good to me now

2023-08-04 03:48 UTC, haroonmaqsoodch reviewed
Resolve the conflicts

2023-08-04 20:07 UTC, merged