Create my profile screen
haroonmaqsoodch/ShopGo pull request #18
Opened 2023-08-04 10:54 UTC by zoha565

## Task no: [SG-13] (https://shopgoswift.atlassian.net/browse/SG-13)

## Description:
1) Gave autolayout to the entire screen
2) Created an extension for the view controller and did all the UI customizations in it.

## Screenshots/gifts: 

![Simulator Screenshot - iPhone 14 Pro - 2023-08-04 at 15 54 03](https://github.com/haroonmaqsoodch/ShopGo/assets/139580659/bde42019-2458-401d-bcbd-2a79f45a01b8)

2023-08-04 11:33 UTC, zuhair5 requested changes
- Your createprofile+extension file is not shown kindly recheck it and commit that too
- The autolayout is not correct it should not be showing any errors which i am seeing 
- The profile picture has problems with it's corner radius, either the picture is too big or something else, plus try using a picture in **Png** format. 
- Lastly you don't need the tab bar controller at the bottom as it is a separate story so kindly remove that, it is my mistake i should have mentioned it in the story. 

**tab bar screenshot**
<img width="319" alt="Screenshot 2023-08-04 at 4 33 09 PM" src="https://github.com/haroonmaqsoodch/ShopGo/assets/63094797/89c6f39b-298c-48b6-9e99-3f50b9653d47">


**Kindly fix all the issues mentioned above and re-commit.**

2023-08-05 10:42 UTC, zoha565 commented
fixed

2023-08-05 17:45 UTC, aliahmed1105 commented on ShopGo/CreateMyProfile/CreateProfile+extension.swift
Remove this extra space.

2023-08-05 17:49 UTC, aliahmed1105 commented on ShopGo/CreateMyProfile/CreateProfile+extension.swift
I would suggest adding space after import UIKit.

2023-08-05 18:09 UTC, haroonmaqsoodch reviewed
<img width="283" alt="Screenshot 2023-08-05 at 2 08 09 PM" src="https://github.com/haroonmaqsoodch/ShopGo/assets/90124369/0aa4bbbf-1306-4c61-902e-de5be2f2e432">

These should be buttons not labels. We are going to use them for navigation to other screens. Change them to buttons and create their connections as well.

2023-08-05 20:53 UTC, zoha565 commented
fixed

2023-08-05 20:54 UTC, zoha565 commented on ShopGo/CreateMyProfile/CreateProfile+extension.swift
fixed

2023-08-05 20:54 UTC, zoha565 commented on ShopGo/CreateMyProfile/CreateProfile+extension.swift
fixed

2023-08-05 21:03 UTC, zuhair5 approved these changes
**LGTM**

2023-08-06 18:13 UTC, haroonmaqsoodch approved these changes

2023-08-06 18:13 UTC, merged